# Generated by Django 4.2.6 on 2023-10-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
