# Generated by Django 4.2.6 on 2023-10-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_asignacion_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='cursos',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
