# Generated by Django 4.2.6 on 2023-10-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
