# Generated by Django 4.2.6 on 2023-10-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='dpi',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
