# Generated by Django 4.2.6 on 2023-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres y Apellidos')),
                ('dpi', models.CharField(max_length=13, unique=10, verbose_name='DPI')),
                ('date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=8, verbose_name='Telefono')),
                ('user', models.CharField(max_length=10, verbose_name='Nombre de usuario')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo electronico')),
                ('contraseña', models.CharField(max_length=25, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'db_table': 'alumno',
                'ordering': ['id'],
            },
        ),
    ]
