# Generated by Django 4.2.6 on 2023-10-19 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_type_employee_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Alumnos',
        ),
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres y Apellidos')),
                ('dpi', models.CharField(max_length=13, unique=10, verbose_name='DPI')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo electronico')),
                ('contraseña', models.CharField(max_length=25, verbose_name='Contraseña')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.type')),
            ],
            options={
                'verbose_name': 'catedratico',
                'verbose_name_plural': 'catedraticos',
                'db_table': 'catedratico',
                'ordering': ['id'],
            },
        ),
    ]
